sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    all_branches: true
    tags: false

notifications:
  email:
    recipients:
    - dev@obiba.org
    on_success: change
    on_failure: always
